build: Debug tests should use debug vulkan_profiles.cpp
The original test code was always using the generated source/vulkan_profiles.cpp
regardless of the build configuration.  These changes switch it to use
the generated debug source in source/debug/vulkan_profiles.cpp if building
a Debug build.

The debug source produces messages when a profile cannot be matched on a
particular device, which is useful in debugging test failures, which otherwise
only produce test failure messages:

    ERROR: Checking device support for profile VP_ANDROID_baseline_2021 (deviceName=NVIDIA Tegra X1 (rev B) (nvgpu), driverName=NVIDIA, driverInfo=418.00). You may find the details of the capabilities of this device on https://vulkan.gpuinfo.org/
    ERROR: *** Failure in /home/lunarg/.jenkins/workspace/manual-VulkanProfiles/VulkanProfiles/library/test/test_api_create_device_android.cpp:292 Expected equality of these values:
    ERROR:   1U
    ERROR:     Which is: 1
    ERROR:   supported
    ERROR:     Which is: 0
    ERROR: [  FAILED  ]library_api.vpGetPhysicalDeviceProfileSupport (1 ms)

When the debug code is used, the reasons for the failure are obvious:

    ERROR: Checking device support for profile VP_ANDROID_baseline_2021 (deviceName=NVIDIA Tegra X1 (rev B) (nvgpu), driverName=NVIDIA, driverInfo=418.00). You may find the details of the capabilities of this device on https://vulkan.gpuinfo.org/
    ERROR: Unsupported format condition for VK_FORMAT_A1R5G5B5_UNORM_PACK16: VkFormatProperties2KHR::formatProperties.linearTilingFeatures contains (VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT | VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT | VK_FORMAT_FEATURE_BLIT_DST_BIT | VK_FORMAT_FEATURE_TRANSFER_SRC_BIT | VK_FORMAT_FEATURE_TRANSFER_DST_BIT)
    ...
    ERROR: *** Failure in /home/lunarg/.jenkins/workspace/manual-VulkanProfiles/VulkanProfiles/library/test/test_api_create_device_android.cpp:292 Expected equality of these values:
    ERROR:   1U
    ERROR:     Which is: 1
    ERROR:   supported
    ERROR:     Which is: 0
    ERROR: [  FAILED  ]library_api.vpGetPhysicalDeviceProfileSupport (1 ms)